### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by peterdebruijn** [Kevin-Bronsdijk/SeaMist#1]
The solution does not support the Azure functionality yet. I implemented it myself perhaps you want to merge it into the solution. I added a AzureStore property to the OptimizeRequestBase class:

`[JsonProperty("azure_store")]
        public AzureStore AzureStore { get; set; }
`

And I created a new class in the model: AzureStore 

'using Newtonsoft.Json;

namespace SeaMist.Model
{
    public class AzureStore
    {

```
    [JsonProperty("account")]
    public string Account { get; set; }

    [JsonProperty("key")]
    public string Key { get; set; }

    [JsonProperty("container")]
    public string Container { get; set; }

    [JsonProperty("path")]
    public string Path { get; set; }


}
```

}
'

**Comment by Kevin-Bronsdijk** [comment]
Thanks @peterdebruijn ! I've added support for Azure Blob storage as well as Amazon S3 for all optimization wait requests. This required a different approach and therefore implemented a new IDataStore interface. The DataStore instances will contain data store specific configuration (now Azure and Amazon, and in the future Rackspace and SoftLayer). For now, I’ve created separate OptimizeWaitRequest classes for each type as well, this to avoid serialization issues on base classes and a place to keep DataStore specific logic.       

Once again, thanks for reporting this shortcoming!
