### ISSUE TITLE
AWS S3 Integration

### ISSUE THREAD

**Issue by sehcheese** [Kevin-Bronsdijk/SeaMist#2]
Kraken supports [uploading directly to AWS S3 after compression](https://kraken.io/docs/storage-s3). This could be added as additional functionality.

**Comment by Kevin-Bronsdijk** [comment]
Thanks for reporting this shortcoming!

I've added support for Azure Blob storage as well as Amazon S3 for all optimization wait requests. The DataStore instances will contain data store specific configuration (now Azure and Amazon, and in the future Rackspace and SoftLayer). Adding code samples later today.
